version: '3.1'
services:
  app:
    container_name: app-topjava-docker
    image: app-topjava-docker
    build: ./
    environment:
    - spring.datasource.url=jdbc:postgresql://dbpostgresql:5432/topjavadocker
    ports:
    - "8080:8080"
    depends_on:
    - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=user
    - POSTGRES_DB=topjavadocker